Fix for "Use imports into private scope." #510
sdatkinson/neural-amp-modeler pull request #515
Opened 2024-12-10 02:08 UTC by zghannam

Refactored the imports for first and third-party imports, but not in-package imports yet. Can absolutely change anything if needed. Didn't break anything as far as I can tell (still passing all provided test cases) and was formatted with Black.

2024-12-10 02:52 UTC, sdatkinson commented
Cool! Yes, this is in the right direction so I'll approve. 

My eyes caught a few stragglers like `numpy as np`.

Since there's so much line diff already, I don't mind merging this PR and taking another PR for more so that it's easier to process piece by piece for me.

2024-12-10 02:54 UTC, sdatkinson commented
Ah, actually one other thing we'll want to do is bump the minor version to 0.12.0 since this is breaking. That needs to happen in `nam_version.py` and in the docs `conf.py`.

2024-12-10 03:38 UTC, zghannam commented
Yeah sorry about the larger PR. I left the "import numpy as np" and other similar imports since that was actually there already and I didn't know if I should be changing any existing names.

So just to make sure whats left: fix some of the existing import names like "import numpy as np", change the version in the mentioned files, and finish up adding names for imports within the package like "from .lightning_module import LightningModule as _LightningModule"?

2024-12-10 05:28 UTC, sdatkinson commented
@zghannam yep! The version bit would be enough for me to merge the PR but all of that and I think it's sufficient to resolve the Issue 👍🏻

2024-12-17 06:07 UTC, sdatkinson requested changes
Thanks for all this work; it's quite a diff!

Just a couple things with "[C]" that I'd like to see addressed before I can approve. Nits, feel free to address optionally; I'd be happy to merge either way.

2024-12-17 06:07 UTC, sdatkinson commented on .vscode/settings.json
> +{
[C] Please remove this file

2024-12-17 06:07 UTC, sdatkinson commented on nam/_version.py
> +__version__ = "0.12.0"
[C] With #516 it looks like we don't need to do this explicitly; go ahead and merge `main` and remove this to resolve the conflict.

2024-12-17 06:07 UTC, sdatkinson commented on nam/cli.py
> +    import os as _os
Nit: since this is import is into the scope of `_ensure_graceful_shutdown()` there's no need to `as _os`

2024-12-17 06:07 UTC, sdatkinson commented on nam/cli.py
> +    import importlib as _importlib
[Nit] Same, these are inside `_apply_extensions()` so already guarded

2024-12-17 06:07 UTC, sdatkinson commented on nam/models/conv_net.py
> +    CONV_NAME as CONV_NAME,
`as _CONV_NAME`

2024-12-17 06:07 UTC, sdatkinson commented on nam/train/lightning_module.py
>      apply_pre_emphasis_filter,
[Nit] Couple more here to get on L33-36

2024-12-17 17:09 UTC, zghannam commented on nam/train/lightning_module.py
>      apply_pre_emphasis_filter,
Just a heads up, I made a small change in the "test_mrstft_loss_cpu_fallback" test to reflect the name change of "multi_resolution_stft_loss as _multi_resolution_stft_loss"

2024-12-18 16:45 UTC, merged